### ISSUE TITLE
TeamAPI return a lot of data

### ISSUE THREAD

**Issue by stanislavBozhanov** [HackSoftware/Loki#49]
Team АПИ-то връща 1 тон дата 500 000 чара, защото връща всеки човек от отбора и на него всичките му данни съответно 
![image](https://cloud.githubusercontent.com/assets/4410455/11855769/c678e3c0-a454-11e5-9121-b466dffebc75.png)

съответно това забавя зареждането на страницата до голяма степен. На моменти ми се наложи по 20 секунди да я зареждам. На лан кабел 6 сек Load

**Comment by RadoRado** [comment]
:panda_face: on it. Thanks :+1:

**Comment by RadoRado** [comment]
@pgergov @Martin95056 @kbadova можете ли да видите с новот NG2 дали все още е проблем :panda_face:

**Comment by pgergov** [comment]
@RadoRado няма драма, връщаме само това, което ни трябва.

**Comment by RadoRado** [comment]
:+1:
